// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diwryjzthqseboohfbmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpd3J5anp0aHFzZWJvb2hmYm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzAyMDEsImV4cCI6MjA2OTY0NjIwMX0.fAVlBupvtuRJueGSdRPqJbID8P3ESjk8AybCpqMmtTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});